services:
    postgres:
        image: postgres:latest
        container_name: postgresql_arborfoods
        restart: unless-stopped
        environment:
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
            POSTGRES_DB: ${POSTGRES_DB}
        ports:
            - "5432:5432"
        volumes:
            - volumeLocation:/var/lib/postgresql/data

volumes:
    volumeLocation:
